-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agenda_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  start timestamp with time zone NOT NULL,
  end timestamp with time zone NOT NULL,
  category character varying DEFAULT 'general'::character varying CHECK (category::text = ANY (ARRAY['meeting'::character varying, 'call'::character varying, 'task'::character varying, 'reminder'::character varying, 'general'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  attendees ARRAY,
  location character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agenda_events_pkey PRIMARY KEY (id),
  CONSTRAINT agenda_events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.agents(id)
);
CREATE TABLE public.agent_executions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agentid uuid,
  ticketid uuid,
  action character varying NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying, 'cancelled'::character varying]::text[])),
  input jsonb DEFAULT '{}'::jsonb,
  result jsonb DEFAULT '{}'::jsonb,
  error_message text,
  execution_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  CONSTRAINT agent_executions_pkey PRIMARY KEY (id),
  CONSTRAINT agent_executions_agentid_fkey FOREIGN KEY (agentid) REFERENCES public.agents(id),
  CONSTRAINT agent_executions_ticketid_fkey FOREIGN KEY (ticketid) REFERENCES public.tickets(id)
);
CREATE TABLE public.agents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['sales'::character varying, 'support'::character varying, 'general'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'paused'::character varying]::text[])),
  config jsonb DEFAULT '{}'::jsonb,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT agents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.banners (
  id integer NOT NULL DEFAULT nextval('banners_id_seq'::regclass),
  titulo character varying NOT NULL,
  subtitulo character varying,
  descricao text,
  badge_texto character varying,
  cor_primaria character varying DEFAULT '#4F46E5'::character varying,
  cor_secundaria character varying DEFAULT '#06B6D4'::character varying,
  icone character varying DEFAULT 'truck'::character varying,
  tipo_promocao character varying DEFAULT 'frete_gratis'::character varying,
  valor_minimo numeric,
  percentual_desconto numeric,
  valor_desconto numeric,
  produtos_aplicaveis text,
  data_inicio timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  data_fim timestamp without time zone,
  ativo boolean DEFAULT true,
  posicao integer DEFAULT 1,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT banners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_config (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_name text NOT NULL,
  segment text,
  document text,
  address jsonb,
  contacts jsonb,
  social_media jsonb,
  working_hours jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_config_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firstname character varying NOT NULL,
  lastname character varying NOT NULL,
  email character varying UNIQUE,
  phone character varying,
  status character varying NOT NULL DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'contacted'::character varying, 'qualified'::character varying, 'proposal'::character varying, 'negotiation'::character varying, 'closed_won'::character varying, 'closed_lost'::character varying]::text[])),
  source character varying DEFAULT 'unknown'::character varying CHECK (source::text = ANY (ARRAY['website'::character varying, 'referral'::character varying, 'social_media'::character varying, 'advertising'::character varying, 'cold_call'::character varying, 'event'::character varying, 'unknown'::character varying]::text[])),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  company character varying,
  position character varying,
  notes text,
  tags ARRAY,
  custom_fields jsonb DEFAULT '{}'::jsonb,
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.agents(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticketid uuid,
  content text NOT NULL,
  sender character varying NOT NULL CHECK (sender::text = ANY (ARRAY['customer'::character varying, 'agent'::character varying, 'system'::character varying]::text[])),
  senderid character varying,
  sendername character varying,
  messagetype character varying DEFAULT 'text'::character varying CHECK (messagetype::text = ANY (ARRAY['text'::character varying, 'image'::character varying, 'audio'::character varying, 'video'::character varying, 'document'::character varying, 'system'::character varying]::text[])),
  mediaurl text,
  mediatype character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  isread boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_ticketid_fkey FOREIGN KEY (ticketid) REFERENCES public.tickets(id)
);
CREATE TABLE public.order_items (
  id integer NOT NULL DEFAULT nextval('order_items_id_seq'::regclass),
  order_id integer NOT NULL,
  product_id integer NOT NULL,
  product_codigo character varying,
  product_cod_barras character varying,
  product_descricao text NOT NULL,
  product_apresentacao character varying,
  product_laboratorio character varying,
  product_tipo character varying,
  unit_price numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  subtotal numeric NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id integer NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
  order_number character varying NOT NULL UNIQUE,
  customer_name character varying NOT NULL,
  customer_email character varying,
  customer_phone character varying,
  customer_address text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'processing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  payment_method character varying DEFAULT 'cash'::character varying CHECK (payment_method::text = ANY (ARRAY['cash'::character varying, 'credit_card'::character varying, 'debit_card'::character varying, 'pix'::character varying, 'bank_transfer'::character varying]::text[])),
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  subtotal numeric NOT NULL DEFAULT 0.00,
  discount numeric DEFAULT 0.00,
  tax numeric DEFAULT 0.00,
  shipping_cost numeric DEFAULT 0.00,
  total numeric NOT NULL DEFAULT 0.00,
  notes text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.produtos (
  id integer NOT NULL DEFAULT nextval('produtos_id_seq'::regclass),
  codigo character varying,
  cod_barras character varying,
  descricao text,
  apresentacao character varying,
  laboratorio character varying,
  tipo character varying,
  quantidade integer,
  reg_ms character varying,
  dt_cadastro timestamp without time zone,
  preco numeric,
  current_sync_time timestamp without time zone,
  texto_busca text,
  CONSTRAINT produtos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'pending'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  category character varying DEFAULT 'general'::character varying,
  customerid character varying,
  customername character varying,
  customeremail character varying,
  customerphone character varying,
  assignedto uuid,
  tags ARRAY,
  metadata jsonb DEFAULT '{}'::jsonb,
  resolution text,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_assignedto_fkey FOREIGN KEY (assignedto) REFERENCES public.agents(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  name text,
  email text,
  role text DEFAULT 'user'::text CHECK (role = ANY (ARRAY['admin'::text, 'user'::text, 'agent'::text])),
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);